baseurl:
title: Latitudes
subtitle: "Travel, outdoors, and life"
author: Tomasz Janczuk
simple_search: http://google.com/search
description: Wer das Dichten will verstehen muss ins Land der Dichter gehen
name: Latitudes
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:title
timezone: America/Seattle
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
